@host = http://localhost:5000

### POST ID
@postId=5efa31418bd0e022641cb8eb

### ALL POSTS
GET {{host}}/posts http/1.1

### ONE POST
GET {{host}}/posts/{{postId}} http/1.1

### POST REQUEST
POST {{host}}/posts http/1.1
content-type: application/json

{
    "title": "This is the title of new post.",
    "description": "This is the description of new post"
}

### UPDATING A POST
PATCH {{host}}/posts/{{postId}} http/1.1
content-type: application/json

{
    "title": "Updated Title",
    "description": "Updated Description"
}

### DELETING A POST
DELETE {{host}}/posts/{{postId}} http/1.1

### ENTER A USER
POST {{host}}/users http/1.1
content-type: application/json

{
    "name": "Muhammad Osama",
    "email": "imuhammadosama@outlook.com",
    "password": "password"
}

